oserou/oserou/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('play/', include('oserou_forplay.urls')),
    path('admin/', admin.site.urls),
]

oserou/oserou_forplay/urls.py
from django.urls import path

from .views import play, login, match

app_name = "oserou_forplay"

urlpatterns = [
    #play
    path('', play.index, name='index'),
    path('board', play.board, name='board'),
    path('board_refresh', play.boardRefresh, name='board_refresh'),
    path('result', play.result, name='result'),

    #match
    path('apply', match.matchApply, name='match_apply'),
    path('match/<int:first_player_id>/<int:second_player_id>', match.matchBoard, name='match_index'),
    path('match/board_refresh', match.matchBoardRefresh, name='match_board_refresh'),
    path('match/result/<int:first_player_id>/<int:second_player_id>', match.matchResult, name='match_result'),

    #ログイン周り
    path('signup/', login.signup_view.as_view(), name='signup'),
    path('login/', login.login_view.as_view(), name='login'),
    path('logout/', login.logout_view.as_view(), name='logout'),
    path('mypage/', login.user_view.as_view(), name='user'),
    path('other/', login.other_view.as_view(), name='other'),
]

oserou/oserou_forplay/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class PlayerUser(AbstractUser):
    pass

class Result(models.Model):
    score = models.IntegerField()
    winner_id = models.ForeignKey(PlayerUser, on_delete=models.CASCADE, related_name = "winner")
    loser_id = models.ForeignKey(PlayerUser, on_delete=models.CASCADE, related_name = "loser")
    created_at = models.DateTimeField()
    deleated_at = models.DateTimeField(null=True)

oserou/oserou_forplay/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):
     class Meta:
        pass

oserou/oserou_forplay/views.py
import asyncio
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from oserou_forplay.modules import placestone, calcscore, findinvalidinput as fii, calcresult

from django.urls import reverse
import numpy as np


# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the play index.")

def board(request):
    template = loader.get_template('oserou_forplay/ban.html')
    context = {
        'board_state_key': [[1 for i in range(8)] for j in range(8)],
    }
    return HttpResponse(template.render(context, request))

def boardRefresh(request):
    #board_stateは文字列として渡されているので注意
    color = int(request.POST.get('color'))
    selected_collumn = int(request.POST.get('selected_collumn'))
    selected_row = int(request.POST.get('selected_row'))
    board_state = request.POST.get('board_state')
    board_state = board_state.split(",")
    board_state = np.array(board_state, dtype=np.int64).reshape(8, 8)                
    #valid 0:OK, 1:not valid input, 2:pass, 3:finish, 4:invalid pass
    valid = fii.checkValid(board_state, selected_row, selected_collumn, color)
    if valid == 0:
        new_board_state = placestone.board_placestone(board_state, selected_row, selected_collumn, color)
        board_state = new_board_state
    d = {
        'new_board_state': board_state.tolist(),
        'return_code' : valid,
    }
    return JsonResponse(d)

def result(request):
    board_state = request.POST.get('result')
    board_state = board_state.split(",")
    board_state = np.array(board_state, dtype=np.int64).reshape(8, 8)
    [winner, score] = calcresult.winner(board_state)
    template = loader.get_template('oserou_forplay/result.html')
    context = {
        'winner' : winner,
        'score' : score,
    }
    return HttpResponse(template.render(context, request))

oserou/oserou_forplay/views/login.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.views.generic import View
from ..forms import SignupForm, LoginForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class signup_view(View):
    def get(self, request):
        form = SignupForm()
        param = {
                'form': form
        }
        #return HttpResponse("hello")
        return render(request, "oserou_forplay/signup.html", param)

    def post(self, request):
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            print("saved")
        else:
            print(form.cleaned_data)
            return HttpResponse("Oh no!")

        return HttpResponseRedirect("/play/login")

class login_view(View):
    def get(self, request):
        form = LoginForm()
        param = {
        'form': form,
        }

        return render(request, 'oserou_forplay/login.html', param)

    def post(self, request):
        next = request.POST.get('next')
        form = LoginForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()

            if user:
                login(request, user)
                return HttpResponseRedirect('/play/mypage')

        else:
            print(form.cleaned_data)
            return HttpResponse("Oh no!")
        

class logout_view(View):
     def get(self, request):
        logout(request)
        return HttpResponseRedirect("/play")

class user_view(View):
    @method_decorator(login_required)
    def get(self, request):
        user = self.request.user

        param = {
            "username" : user.get_username(), 
        }

        return render(request, 'oserou_forplay/user.html', param)

class other_view(View):
    def get(self, request):
         pass

oserou/oserou_forplay/views/match.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from oserou_forplay.modules import placestone, calcscore, findinvalidinput as fii, calcresult
from django.urls import reverse
import numpy as np
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from ..models import PlayerUser, Result
from datetime import datetime

@login_required
def matchApply(request):
    all_players = PlayerUser.objects.all()
    context = {
        'players': all_players
    }
    template = loader.get_template('oserou_forplay/apply.html')
    return HttpResponse(template.render(context, request))

@login_required
def matchBoard(request, first_player_id, second_player_id):
    first_player = PlayerUser.objects.filter(pk = first_player_id).get()
    second_player = PlayerUser.objects.filter(pk = second_player_id).get()
    context = {
        'first_player': first_player,
        'second_player': second_player,
        'board_state_key': [[1 for i in range(8)] for j in range(8)],
    }
    template = loader.get_template('oserou_forplay/match.html')
    return HttpResponse(template.render(context, request))

@login_required
def matchBoardRefresh(request, first_player_id, second_player_id):
    #board_stateは文字列として渡されているので注意
    color = int(request.POST.get('color'))
    selected_collumn = int(request.POST.get('selected_collumn'))
    selected_row = int(request.POST.get('selected_row'))
    board_state = request.POST.get('board_state')
    board_state = board_state.split(",")
    board_state = np.array(board_state, dtype=np.int64).reshape(8, 8)                
    #valid 0:OK, 1:not valid input, 2:pass, 3:finish, 4:invalid pass
    valid = fii.checkValid(board_state, selected_row, selected_collumn, color)
    if valid == 0:
        new_board_state = placestone.board_placestone(board_state, selected_row, selected_collumn, color)
        board_state = new_board_state
    first_player = PlayerUser.objects.filter(pk = first_player_id).get()
    second_player = PlayerUser.objects.filter(pk = second_player_id).get()
    d = {
        'new_board_state': board_state.tolist(),
        'return_code' : valid,
        'first_player': first_player,
        'second_player': second_player,
    }
    return JsonResponse(d)


@login_required
def matchResult(request, first_player_id, second_player_id):
    board_state = request.POST.get('result')
    board_state = board_state.split(",")
    board_state = np.array(board_state, dtype=np.int64).reshape(8, 8)
    [winner, matchscore] = calcresult.winner(board_state)
    template = loader.get_template('oserou_forplay/result.html')
    context = {
        'winner' : winner,
        'score' : matchscore,
        'first_player' : PlayerUser.objects.filter(pk = first_player_id).get(),
        'second_player': PlayerUser.objects.filter(pk = second_player_id).get()
    }

    #データベースへの保存
    if winner == "first player":
        winner_instance = PlayerUser.objects.filter(pk = first_player_id).get()
        loser_instance = PlayerUser.objects.filter(pk = second_player_id).get()
    elif winner == "second player":
        winner_instance = PlayerUser.objects.filter(pk = second_player_id).get()
        loser_instance = PlayerUser.objects.filter(pk = first_player_id).get()
    else:
        print("draw")
        return HttpResponse(template.render(context, request))
    Result.objects.create(winner_id = winner_instance, loser_id = loser_instance,
                          score = matchscore, created_at = datetime.now())
    return HttpResponse(template.render(context, request))

oserou/oserou_forplay/views/play.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from oserou_forplay.modules import placestone, calcscore, findinvalidinput as fii, calcresult
from django.urls import reverse
import numpy as np
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from ..models import PlayerUser, Result


# Create your views here.

@login_required
def index(request):
    return HttpResponse("Hello, world. You're at the play index.")

@login_required
def board(request):
    template = loader.get_template('oserou_forplay/ban.html')
    context = {
        'board_state_key': [[1 for i in range(8)] for j in range(8)],
    }
    return HttpResponse(template.render(context, request))

@login_required
def boardRefresh(request):
    #board_stateは文字列として渡されているので注意
    color = int(request.POST.get('color'))
    selected_collumn = int(request.POST.get('selected_collumn'))
    selected_row = int(request.POST.get('selected_row'))
    board_state = request.POST.get('board_state')
    board_state = board_state.split(",")
    board_state = np.array(board_state, dtype=np.int64).reshape(8, 8)                
    #valid 0:OK, 1:not valid input, 2:pass, 3:finish, 4:invalid pass
    valid = fii.checkValid(board_state, selected_row, selected_collumn, color)
    if valid == 0:
        new_board_state = placestone.board_placestone(board_state, selected_row, selected_collumn, color)
        board_state = new_board_state
    d = {
        'new_board_state': board_state.tolist(),
        'return_code' : valid,
    }
    return JsonResponse(d)

@login_required
def result(request):
    board_state = request.POST.get('result')
    board_state = board_state.split(",")
    board_state = np.array(board_state, dtype=np.int64).reshape(8, 8)
    [winner, score] = calcresult.winner(board_state)
    template = loader.get_template('oserou_forplay/result.html')
    context = {
        'winner' : winner,
        'score' : score,
    }
    return HttpResponse(template.render(context, request))

oserou/oserou_forplay/templates/oserou_forplay/apply.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>apply</title>
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        </head>
    <body>
        you : {{user.username}}
        <h1> choose the opponent:</h1>
        <ul>
            {% for player in players %}
                <li><a href="/play/match/{{user.id}}/{{player.id}}">{{ player.username }}</a></li>
            {% endfor %}
        </ul>
    </body>
</html>

oserou/oserou_forplay/templates/oserou_forplay/ban.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>reversi field</title>
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" >

        <!--　静的ファイル読み込み -->
        {% load static %}

        <!-- JavaScript読み込み -->
        <script src="{% static 'js/ban.js' %}"></script>

        <!-- CSS読み込み -->
        <link rel="stylesheet" href="{% static 'css/ban.css' %}">

        <!-- contextの変数をjavascriptで扱う際、中身を一旦変数化しておく必要がある-->
        <script>
            let board_state = {{ board_state_key }}
        </script>
    </head>
    <body onload="init()">
        <h1> here is ban </h1>
        <table id="board"></table>
        <form id ="board_refresh" action="{% url 'oserou_forplay:board_refresh' %}" method="post">
            {% csrf_token %}
                <input type="hidden" id="board_state_send">
                <input type="hidden" id="selected_row_send">
                <input type="hidden" id="selected_collumn_send">
                <input type="hidden" id="color_send" value ="2">
            <input type="submit" value="submit your choice">
        </form>

        <form id ="end_game" action="{% url 'oserou_forplay:result' %}" method="post">
            {% csrf_token %}
                <input type="hidden" name = 'result' id="board_state_result">
            <input type="submit" value="show result(end game)">
        </form>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var csrftoken = getCookie('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $('#board_refresh').on('submit', function(e) {
                e.preventDefault();

                $.ajax({
                    'url': '{% url "oserou_forplay:board_refresh" %}',
                    'type': 'POST',
                    'data': {
                        'board_state': $('#board_state_send').val(),
                        'selected_row': $('#selected_row_send').val(),
                        'selected_collumn': $('#selected_collumn_send').val(),
                        'color': $('#color_send').val(),
                    },
                    'dataType': 'json'
                })
                .done(function(response){
                    let player = "first move";
                    board_state = response.new_board_state;
                    let valid = response.return_code;
                    refreshBoard(board_state);
                    if (valid == 0){
                        turn++;
                    }
                    else if(valid == 1){
                        alert("invalid input. choose another cell.")
                    }
                    else if(valid == 2){
                        alert("passed(there are no valid cells.)")
                        turn++;
                        pass++;
                    }
                    else if(valid == 3){
                        alert("finish")
                    }
                    else if(valid == 4){
                        alert("submit your action.")
                    }
                    else{
                        alert("oh no")
                    }

                    if ((turn)%2 == 0){
                        player = "first move";
                    }
                    else{
                        player = "second move";      
                    }
                    alert("turn " + (turn+1) + "\n" + player + "'s turn");
                });
            });
        </script>
    </body>
</html>

oserou/oserou_forplay/templates/oserou_forplay/login.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ログイン</title>
</head>
<body>
    <h1>ログイン</h1>
    <p>{{message}}</p>
    <form action="{% url 'oserou_forplay:login' %}" method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <p><input type="hidden" name="next" value="{{next}}"></p>
        <p><input type="submit" value="ログイン"></p>
    </form>
    <p><a href="{% url 'oserou_forplay:signup'%}">ユーザー登録</a></p>
</body>
</html>

oserou/oserou_forplay/templates/oserou_forplay/match.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>reversi field</title>
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" >

        <!--　静的ファイル読み込み -->
        {% load static %}

        <!-- JavaScript読み込み -->
        <script src="{% static 'js/ban.js' %}"></script>

        <!-- CSS読み込み -->
        <link rel="stylesheet" href="{% static 'css/ban.css' %}">

        <!-- contextの変数をjavascriptで扱う際、中身を一旦変数化しておく必要がある-->
        <script>
            let board_state = {{ board_state_key }}
        </script>
    </head>
    <body onload="init()">
        <h1> here is ban </h1>
        <table id="board"></table>
        <form id ="board_refresh" action="{% url 'oserou_forplay:match_board_refresh' %}" method="post">
            {% csrf_token %}
                <input type="hidden" id="board_state_send">
                <input type="hidden" id="selected_row_send">
                <input type="hidden" id="selected_collumn_send">
                <input type="hidden" id="color_send" value ="2">
            <input type="submit" value="submit your choice">
        </form>

        <form id ="end_game" action="/play/match/result/{{first_player.id}}/{{second_player.id}}" method="post">
            {% csrf_token %}
                <input type="hidden" name = 'result' id="board_state_result">
            <input type="submit" value="show result(end game)">
        </form>
        <p>first player: {{first_player.username}}</p>
        <p>second player: {{second_player.username}}</p>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var csrftoken = getCookie('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $('#board_refresh').on('submit', function(e) {
                e.preventDefault();

                $.ajax({
                    'url': '{% url "oserou_forplay:board_refresh" %}',
                    'type': 'POST',
                    'data': {
                        'board_state': $('#board_state_send').val(),
                        'selected_row': $('#selected_row_send').val(),
                        'selected_collumn': $('#selected_collumn_send').val(),
                        'color': $('#color_send').val(),
                    },
                    'dataType': 'json'
                })
                .done(function(response){
                    let player = "first move";
                    board_state = response.new_board_state;
                    let valid = response.return_code;
                    refreshBoard(board_state);
                    if (valid == 0){
                        turn++;
                    }
                    else if(valid == 1){
                        alert("invalid input. choose another cell.")
                    }
                    else if(valid == 2){
                        alert("passed(there are no valid cells.)")
                        turn++;
                        pass++;
                    }
                    else if(valid == 3){
                        alert("finish")
                    }
                    else if(valid == 4){
                        alert("submit your action.")
                    }
                    else{
                        alert("oh no")
                    }

                    if ((turn)%2 == 0){
                        player = "first move";
                    }
                    else{
                        player = "second move";      
                    }
                    alert("turn " + (turn+1) + "\n" + player + "'s turn");
                });
            });
        </script>
    </body>
</html>

oserou/oserou_forplay/templates/oserou_forplay/result.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>result</title>
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        </head>
    <body>
        <h1>here is result</h1>
        <h2>winner : {{winner}}</h2>
        <h2>score : {{score}}</h2>
    </body>
</html>

oserou/oserou_forplay/templates/oserou_forplay/signup.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ユーザー登録</title>
</head>
<body>
    <h1>ユーザー登録</h1>
    <form action="{% url 'oserou_forplay:signup' %}" method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="登録"></p>
    </form>
</body>
</html>

oserou/oserou_forplay/templates/oserou_forplay/user.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{username}}</title>
</head>
<body>
    <h1>マイページ</h1>
    <p>{{username}}</p>
</body>

</html>